apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::090074823871:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-Z8uwNB7r1tiC
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
    userarn: arn:aws:iam::090074823871:user/raju
    username: raju
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-08T12:09:28Z"
  name: aws-auth
  namespace: kube-system
  uid: 57d52a38-3317-49aa-80cf-2e3510ab9869




